### ISSUE TITLE
single variable assignment

### ISSUE THREAD

**Issue by nkrusch** [statycc/pymwp#82]
Analyzing single variable assignment

https://github.com/statycc/pymwp/blob/662f1b9fadfe815e42499d1357d1698467ea29f9/c_files/basics/assign_variable.c#L6-L8

gives the matrix below and choices `[0], [1], [2]`.

|     | x  | y |
|-- | -- | -- |
| x | o | o |
| y | m | m |

I don't think the choice applies here? This is by rule E1.

**Comment by aubertc** [comment]
Yes, this is by rule E^S in our paper, and indeed there should be no choice here. I am guessing that axioms are very much hard-coded into thinking they need a choice, and so that the implementation just says in this case "Whatever choice you make will work". It is a bit un-necessary, I agree, but I don't think it is an issue.
